// <auto-generated />
namespace VideothekData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreMovien2m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreMovien2m));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250813411_GenreMovie-n2m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
